it("should throw an error for invalid arity", () => {
  return WebAssembly.instantiate(wasmmodule).then(m => {
    const fn = () => m.instance.exports.add(1, 1, 9, 10);

    assert.throws(fn, "Function 1 called with 4 arguments but 2 expected");
  });
});
